apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
             - name: MYSQL_DATABASE
               value: "boot_work"
             - name: MYSQL_USER   
               value: "admin"
             - name: MYSQL_PASSWORD
               value: "root"
             - name: MYSQL_ROOT_PASSWORD
               value: "root"

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: jenkinsdata
              mountPath: /var/lib/jenkins         # this is your container path from where your data will be stored
      volumes:
        - name: jenkinsdata
          persistentVolumeClaim:
            claimName: jenkins-pvc    # PVC claim name
